### ISSUE TITLE
Was it used in real world? 

### ISSUE THREAD

**Issue by AntonNik0laev** [egoetschalckx/nested-intervals-sql#1]
Hi! I'm really glad to find your implementation of nested intervals, it was not real easy to find how it looks on practice.
I'm just curious were you been able to use this on production? Did you make any performance measures for it?

**Comment by egoetschalckx** [comment]
"No" and "no", sadly. My implementation(s) of it have never gone to production, and I've not done any formal performance metrics.

There is a second implementation in my repository [EchoServer](https://github.com/egoetschalckx/EchoServer) that I have tested with trees of thousands of nodes at tree depths greater than 100 and performance seems "good" but that is hardly scientific so YMMV.

I also have a JPA version in the works, under [nested-intervals-java](https://github.com/egoetschalckx/nested-intervals-java), if you are interested

**Comment by AntonNik0laev** [comment]
Makes sense, Thanks a lot!
